
     Name
          elib/edir - ieee/sectioned library for MPX

     Syntax
          -K/system/bin/e option to nbcc

     Description
          The ieee library for MPX contains the same version of the
          run time library used for clb/cdr.  It has been recompiled
          with the -F flag for nbcc.  Usage of this option tells
          nbcas to generate ieee floating point instructions instead
          of standard Encore floating point instructions.  By using
          the -Ke option to nbcc when building a C task, the ieee
          versions will be selected before the standard versions.
          Using this library allows a C task to be built that will
          run using ieee floating point arithmetic.  The user is
          warned that sectioned code is automatically generated by
          the assembler if the ieee options is specified.  Programs
          may compile and link correctly, but will not execute
          properly.

          If c.srt.o or c.srte.o are included explicitly as part of
          the file list to NBCC, these must be changed to reflect
          usage of the ieee versions.  Change the normal pathname
          of "/system/bin/c.srte.o" to "/system/elib/c.srte.o".

     Files
          c.srt.s               Non extended startup code.
          c.srte.s              Extended startup code.
          makefile.ieee         Makefile for making elib/edir.
          edir                  Ieee MPX directory file.
          elib                  Ieee MPX library file.

     See Also
          nbcas.m, nbcat.m, nbcc.m, nbccom.m, molib.m, moelib.m

     Notes
          Insure all inline assembler used in C functions are making
          proper use of the cequ/dequ directives.

          (printed 05/03/95 - J B Systems)
